### ISSUE TITLE
Client Secret, Refresh Token, Access Token are stored in plaintext

### ISSUE THREAD

**Issue by hotab** [go-oauth2/oauth2#108]
If all the tokens/secrets are stored in plaintext, then in case of database compromise for read-only (typical for many types of injection bugs), it will be possible to escalate the issue to authentication bypass.

It might be desirable to allow the use of hash or encryption functions prior to token storage in the database to be used. 

Ref:
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Password_Storage_Cheat_Sheet.md#hash-the-password-as-one-of-several-steps
https://www.reddit.com/r/learnprogramming/comments/7ye9iw/how_should_oauth2_refresh_tokens_be_stored_in_the/dufvizt/?utm_source=share&utm_medium=web2x
https://stackoverflow.com/a/43009934
https://github.com/thephpleague/oauth2-server/issues/387
https://tools.ietf.org/html/rfc6819#section-5.1.4.1.3

**Comment by imrenagi** [comment]
I'm also wondering the same thing. If I'm not mistaken Spring Boot security also stores these as plain text (CMIIW). Not sure why. Is it by design? But as you said in RFC6819, it says these credentials needs to be hashed or encrypted.. 

This is the current check
```
func (m *Manager) GenerateAccessToken(gt oauth2.GrantType, tgr *oauth2.TokenGenerateRequest) (accessToken oauth2.TokenInfo, err error) {
	cli, err := m.GetClient(tgr.ClientID)
	.....
	} else if tgr.ClientSecret != cli.GetSecret() { //here it is
		err = errors.ErrInvalidClient
		return
	}
        .....
```

And I have an idea for adding a custom secretHandler to the manager:
```
type ValidateClientSecretHandler func(rawSecret, hashedSecret string) (isValid bool)
```
So, we can use it by:
```
func (m *Manager) GenerateAccessToken(gt oauth2.GrantType, tgr *oauth2.TokenGenerateRequest) (accessToken oauth2.TokenInfo, err error) {
	cli, err := m.GetClient(tgr.ClientID)
	.....
	} else if m.ValidateClientSecretHandler(tgr.ClientSecret, cli.GetSecret()) {
		err = errors.ErrInvalidClient
		return
	}
        .....
```

**Comment by kostyay** [comment]
Any progress on this?
I also store the secrets hashed and I need a comparison function.

**Comment by dzhu** [comment]
That doesn't cover everything, unfortunately. For example, [bcrypt](https://en.wikipedia.org/wiki/Bcrypt), which is a good and common choice for hashing passwords, is generally implemented so it doesn't produce a deterministic output; it generates a random salt as part of the algorithm. So you can't reproduce the same hash given the same password (short of trying many times, of course), but have to instead check a password by passing it and the original hash directly to a comparison function.
