### ISSUE TITLE
[Request] multi redirect_url

### ISSUE THREAD

**Issue by myml** [go-oauth2/oauth2#120]
rfc6749 https://tools.ietf.org/html/rfc6749#section-3.1.2.3
> If multiple redirection URIs have been registered. if only part of
   the redirection URI has been registered, or if no redirection URI has
   been registered, the client MUST include a redirection URI with the
   authorization request using the "redirect_uri" request parameter.

I can not use multi redirect_url, is there anything I have not found?

**Comment by vitorarins** [comment]
I believe you must set your own `ValidateURIHandler`: https://github.com/go-oauth2/oauth2/blob/535666c25efd04f4d1e59a533585172cde15b3f4/manage/manager.go#L91

**Comment by myml** [comment]
Thank you
