### ISSUE TITLE
[BUG] Client secret not verified if not provided

### ISSUE THREAD

**Issue by sywesk** [go-oauth2/oauth2#156]
Hello, 

While trying to get your lib working on my project, I saw that using `Server.HandleTokenRequest` with no secret leads to a valid token being generated. See the attached picture as a proof.

I used a sample configuration to get it to work: 

```go
	manager := manage.NewDefaultManager()
	manager.MustTokenStorage(store.NewMemoryTokenStore())

	clientStore := store.NewClientStore()
	clientStore.Set("000000", &models.Client{
		ID:     "000000",
		Secret: "999999",
		Domain: "http://localhost",
	})
	manager.MapClientStorage(clientStore)

	srv := server.NewDefaultServer(manager)
```

Notes: Giving a bad secret results in an error being thrown. But no secret works.

![token_with_no_secret](https://user-images.githubusercontent.com/862607/87880198-fd2a5c80-c9ef-11ea-9a81-4a445cd4eb98.PNG)

**Comment by sheepsong** [comment]
This is a fatal bug🤔
Should stay on v4.1.0 before the pr is merged.

**Comment by sywesk** [comment]
@sheepsong Good thing that issue appeared only recently ! My fear was that it went hidden for a long time but that's not the case. 
Now that this is fixed, let's close this issue :D

**Comment by aubelsb2** [comment]
This is confusing me a bit I wrote up something here: https://github.com/go-oauth2/oauth2/pull/151#issuecomment-661526578
