### ISSUE TITLE
Compilation error while initializing error handlers

### ISSUE THREAD

**Issue by smartaquarius10** [go-oauth2/oauth2#166]
Team,

While initializing these handlers

```
srv.SetInternalErrorHandler(func(err error) (re *errors.Response) {
		log.Println("Internal Error:", err.Error())
		return
	})

	srv.SetResponseErrorHandler(func(re *errors.Response) {
		log.Println("Response Error:", re.Error.Error())
	})

```

These errors are coming. 

> cannot use (func(err error) (re *errors.Response) literal) (value of type func(err error) (re *errors.Response)) as server.InternalErrorHandler value in argument to srv.SetInternalErrorHandlercompiler

> cannot use (func(re *errors.Response) literal) (value of type func(re *errors.Response)) as server.ResponseErrorHandler value in argument to srv.SetResponseErrorHandlercompiler

Can anyone please help me here.

**Comment by tienbm90** [comment]
Which version of go-oauth2 are you using ?

**Comment by ekundayo-ab** [comment]
Try using this `github.com/go-oauth2/oauth2/v4/errors` or `github.com/go-oauth2/oauth2/v3/errors` for the `errors` package

**Comment by smartaquarius10** [comment]
Sure. Thanx. 🙂
