### ISSUE TITLE
newPasswordHandler function add context

### ISSUE THREAD

**Issue by XciD** [go-oauth2/oauth2#173]
Hello, 

It's possible to add the context in the `PasswordAuthorizationHandler` method ?

Current signature:

`PasswordAuthorizationHandler func(username, password string) (userID string, err error)`

Propose one:

`PasswordAuthorizationHandler func(ctx context.Context, username, password string) (userID string, err error)`

It's quite usefull to follow request id or tracing.

I'd be glad to propose you a PR.

**Comment by realbucksavage** [comment]
@XciD I'm working on #207 that addresses this. Hoping that it is according to the library's standards and gets merged soon.

**Comment by realbucksavage** [comment]
@XciD @LyricTian this can be closed now.

**Comment by XciD** [comment]
@realbucksavage thanks
