### ISSUE TITLE
Any interest in adapting a PR?

### ISSUE THREAD

**Issue by tsmethurst** [go-oauth2/oauth2#181]
I just made a release of a forked version of this library that I'm using in a project:

https://github.com/superseriousbusiness/oauth2/releases/tag/v4.3.0-SSB

Basically, it changes some structs into interfaces to allow library users to implement their own Client and ClientStores that use database rather than in-memory storage.

Any interest in me making a PR of this back to here?

It would solve the following:

* https://github.com/go-oauth2/oauth2/issues/89
* https://github.com/go-oauth2/oauth2/issues/165

**Comment by tsmethurst** [comment]
This is how it looks to implement these interfaces from a library-user point of view:

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/oauth/tokenstore.go

https://github.com/superseriousbusiness/gotosocial/blob/main/internal/oauth/clientstore.go

**Comment by adeturner** [comment]
With the positive that I stepped through all the code to discover this situation (must remember to search issues prior to reading code) , I agree it would be nice to override the implementation. What happened with this idea, just lack of response?
