### ISSUE TITLE
invalid_request

### ISSUE THREAD

**Issue by fan4905** [go-oauth2/oauth2#225]
After running, the error invalid_request is reported, and the link goes to 
http://localhost:9096/authorize?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request

**Comment by rochinworks** [comment]
What was the fix for this @fan4905 ?

**Comment by rushairer** [comment]
not yet!

**Comment by rushairer** [comment]
You must `SetUserAuthorizationHandler`  first. @fan4905
