### ISSUE TITLE
Example doesn't work - access_denied

### ISSUE THREAD

**Issue by asiraky** [go-oauth2/oauth2#265]
FYI, the example doesn't work. Copy paste the example code into a server.go, build it and run it then click the link in the readme: `http://localhost:9096/authorize?client_id=000000&response_type=code` and the response is access_denied. 

I would provide more info but there is no Issue template here so Im not sure what other info you want.

**Comment by asiraky** [comment]
PR to fix: https://github.com/go-oauth2/oauth2/pull/266

**Comment by andig** [comment]
Fix has been merged- close?
