### ISSUE TITLE
How did my user relate to the token?

### ISSUE THREAD

**Issue by Jackgris** [go-oauth2/oauth2#50]
First of all, thank you for your work.
Could you give me an example, or explain how I relate the user created in the database with the generated token?
In other words, how do I get the id of the user according to the generated token

**Comment by LyricTian** [comment]
``` go
srv := server.NewDefaultServer(manager)

http.HandleFunc("/verify_token", func(w http.ResponseWriter, r *http.Request) {
	ti, err := srv.ValidationBearerToken(r)
	// userID := ti.GetUserID()
})
```

**Comment by Jackgris** [comment]
Thanks for your answer
The truth is, I do not know why I did not see that function in the code.
It's just what I was looking for.
