### ISSUE TITLE
Generate JWT Access Token

### ISSUE THREAD

**Issue by yeycfri** [go-oauth2/oauth2#51]
Hi, 这个项目很棒，多谢你的贡献。

我现在有一个问题是，我想把DefaultManager的AccessGenerate替换成生成jwt的。而现在这部分的接口定义了只有GenerateBasic这个数据能参与token的生成，如果我想用到别的数据例如scope来参与生成jwt，这里没办法做到。
[https://github.com/go-oauth2/oauth2/blob/master/generate.go#L20](url)

我想问一下，这有什么好的解决方法吗？或者代码中哪里有这方面的拓展？如果没有，后续是否考虑加入呢？

谢谢

**Comment by LyricTian** [comment]
嗯，谢谢你的建议，目前还没有这块的支持。可以考虑增加一个扩展参数，或者你可以提一个pr。
