### ISSUE TITLE
How to use scopes to Provide Role-Based Authorization ?

### ISSUE THREAD

**Issue by julienkosinski** [go-oauth2/oauth2#53]
Hello,

Thank you for all your hard work!
Is there any way to use the scope to provide role-based authorization?
It seems that it's not possible today and scope is only used as a request by the user because models/client.go does not implement the scope.
Maybe it could have in models/client.go a list of authorized scopes for a client?

Thanks!

**Comment by LyricTian** [comment]
It is recommended to implement the ClientInfo interface and extend the client's fields.
You see if you meet your needs!

**Comment by julienkosinski** [comment]
Right, thank you, I'll try to do it someday! :)
