### ISSUE TITLE
uuid.NewV4 updated

### ISSUE THREAD

**Issue by freman** [go-oauth2/oauth2#63]
So I'm getting

```
gopkg.in/oauth2.v3/generates/access.go:28:66: multiple-value uuid.NewV4() in single-value context
gopkg.in/oauth2.v3/generates/access.go:31:68: multiple-value uuid.NewV4() in single-value context
gopkg.in/oauth2.v3/generates/authorize.go:24:32: multiple-value uuid.NewV1() in single-value gopkg.in/oauth2.v3/store/token.go:46:24: multiple-value uuid.NewV4() in single-value context
```

This seems to be fixed in the library, but a bit of investigation has revealed that gopkg.in hasn't been updated . Without putting any effort into researching the issue it seems to be because you have not tagged the fixed code with a version.

Can you please do this?

**Comment by LyricTian** [comment]
The problem has been fixed, thank you!

**Comment by freman** [comment]
http://gopkg.in/oauth2.v3 still lists 3.8.3 as the current version which still hasn't got that fix in it :(

**Comment by Sef1995** [comment]
Same problem for me..

**Comment by ptman** [comment]
if this is fixed, then this could be closed
