### ISSUE TITLE
Support for context

### ISSUE THREAD

**Issue by Merovius** [go-oauth2/oauth2#65]
Many of the fields of server.Server are callbacks that don't take either an `*http.Request` or a `context.Context` as arguments. This means it is impossible to use any request-specific information in them: For example, I'd like to log errors with a request ID, increment metrics with request-specific labels (like the path and method) and set a custom verbosity per request.

It would be great if there was a way to set these fields on a per-request basis. The simplest way would be to add a `context.Context` field, but that would be backwards-incompatible. Another way would be to add a (for example) `CallbacksForRequest(*http.Request) Server` function that could be used to return closures encapsulating all the request-specific data needed. That would be less ergonomical, but work.

**Comment by LyricTian** [comment]
Thank you for your suggestion, I am planning to use context refactoring. You can submit a pull request to meet your needs. Thank you!

**Comment by mkaczanowski** [comment]
Bump. It would be great to have context support

**Comment by mkaczanowski** [comment]
https://github.com/go-oauth2/oauth2/pull/148
