### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by berlincount** [go-oauth2/oauth2#68]
Running through the auth flow, I'm getting

```
2018/03/29 01:10:56 http: panic serving 127.0.0.1:39968: interface conversion: interface {} is nil, not url.Values
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc420192140)
        /usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x744500, 0xc4202587c0)
        /usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
main.authHandler(0x7ed260, 0xc4201b01c0, 0xc4201a2800)
        /home/count/src/github.com/go-oauth2/oauth2/example/server/server.go:119 +0x417
net/http.HandlerFunc.ServeHTTP(0x7bf450, 0x7ed260, 0xc4201b01c0, 0xc4201a2800)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x996e40, 0x7ed260, 0xc4201b01c0, 0xc4201a2800)
        /usr/lib/go-1.10/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4201261a0, 0x7ed260, 0xc4201b01c0, 0xc4201a2800)
        /usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420192140, 0x7ed4e0, 0xc4202586c0)
        /usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b
````

with the given example :(

**Comment by LyricTian** [comment]
## Run Server

``` bash
$ cd example/server
$ go run server.go
```

## Run Client

```
$ cd example/client
$ go run client.go
```

## Open the browser

[http://localhost:9094](http://localhost:9094)

**Comment by berlincount** [comment]
Odd.

I'm not sure what was wrong yesterday, but today it works. Must have contaminated my environment somehow :(

Sorry for the erroneous and incomplete bug report!

**Comment by Bruce-sz** [comment]
I also encountered the same error。

`	/usr/local/go/src/net/http/server.go:2795 +0x27b
2018/04/03 11:36:00 http: panic serving [::1]:64694: interface conversion: interface {} is nil, not url.Values
goroutine 59 [running]:
net/http.(*conn).serve.func1(0xc4202c83c0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x1346300, 0xc420154e80)
	/usr/local/go/src/runtime/panic.go:505 +0x229
main.authHandler(0x13ef560, 0xc42027c380, 0xc4202dc400)
	/Users/bruce/go/src/gopkg.in/oauth2.v3/example/server/server.go:117 +0x474
net/http.HandlerFunc.ServeHTTP(0x13c1488, 0x13ef560, 0xc42027c380, 0xc4202dc400)
	/usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x15997c0, 0x13ef560, 0xc42027c380, 0xc4202dc400)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42011c340, 0x13ef560, 0xc42027c380, 0xc4202dc400)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4202c83c0, 0x13ef820, 0xc42029ec80)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b`
