### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [go-oauth2/oauth2#69]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by adamdecaf** [comment]
This was done in https://github.com/go-oauth2/oauth2/commit/84834429be3fb8542b10e21864b2ffa84cbf74a1 for https://github.com/go-oauth2/oauth2/issues/76
