### ISSUE TITLE
Missing second argument for method uuid.Must()

### ISSUE THREAD

**Issue by beng90** [go-oauth2/oauth2#76]
```
vendor/gopkg.in/oauth2.v3/generates/access.go:28:65: not enough arguments in call to uuid.Must
		have (uuid.UUID)
		want (uuid.UUID, error)
vendor/gopkg.in/oauth2.v3/generates/access.go:31:67: not enough arguments in call to uuid.Must
		have (uuid.UUID)
		want (uuid.UUID, error)
vendor/gopkg.in/oauth2.v3/generates/authorize.go:24:31: not enough arguments in call to uuid.Must
		have (uuid.UUID)
		want (uuid.UUID, error)
vendor/gopkg.in/oauth2.v3/store/token.go:46:23: not enough arguments in call to uuid.Must
		have (uuid.UUID)
		want (uuid.UUID, error)
```

Example from generates/access.go

`access = base64.URLEncoding.EncodeToString(uuid.NewV3(uuid.Must(uuid.NewV4()), buf.String()).Bytes())`

Fixed code:
`access = base64.URLEncoding.EncodeToString(uuid.NewV3(uuid.Must(uuid.NewV4(), err), buf.String()).Bytes())`

**Comment by beng90** [comment]
It won't help.
Must() function require two parameters and satori still has the same in implementation.
https://github.com/satori/go.uuid/blob/36e9d2ebbde5e3f13ab2e25625fd453271d6522e/uuid.go#L156

I can fix it in oauth2 package but I don't know how to contribute.

**Comment by beng90** [comment]
@LyricTian could you do the change in code. This is simple fix.
I can prepare Pull request if you set me as contributor.

**Comment by LyricTian** [comment]
You can try to update the package:
```
go get -v -u github.com/satori/go.uuid
go get -v -u gopkg.in/oauth2.v3
```
I have found no problems with my use here.

```go
// NewV4 returns random generated UUID.
func NewV4() (UUID, error) {
	return global.NewV4()
}
```

```go
func Must(u UUID, err error) UUID {
	if err != nil {
		panic(err)
	}
	return u
}
```

**Comment by adamdecaf** [comment]
@LyricTian I'm trying with go modules and getting the same error. 

https://github.com/go-oauth2/oauth2/blob/v3.8.12/store/token.go#L46
https://github.com/satori/go.uuid/blob/v1.2.0/uuid.go#L156

Those are the latest tags so `go mod` picks them both up.

**Comment by LyricTian** [comment]
OK,I have removed the package:`github.com/satori/go.uuid`.You try again:
`go get -v -u gopkg.in/oauth2.v3`

**Comment by beng90** [comment]
It's much better but I still see one bug
`vendor/gopkg.in/go-oauth2/redis.v1/token.go:44:23: not enough arguments in call to uuid.Must
	have (uuid.UUID)
	want (uuid.UUID, error)`

When function require 2 parameters we cannot pass just one even when it can be nil

**Comment by LyricTian** [comment]
OK.You try again:`go get -u -v gopkg.in/go-oauth2/redis.v3`

**Comment by beng90** [comment]
It is the other bug
`not enough arguments in call to manager.MustTokenStorage
	have (*"vendor/gopkg.in/go-oauth2/redis.v3".TokenStore)
	want (oauth2.TokenStore, error)`

Example usage:
`	manager.MustTokenStorage(redis.NewRedisStore(&redis.Options{
		Addr: config.Redis.Host + ":" + strconv.Itoa(config.Redis.Port),
	}))`

NewRedisStore returns different than NewTokenStore in redis.v1

**Comment by LyricTian** [comment]
you can try `MapTokenStorage`

**Comment by adamdecaf** [comment]
@LyricTian Thanks for the fixes. Could we get a bugfix release tagged?

**Comment by adamdecaf** [comment]
I bumped my project to `v3.9.0` and it worked, thanks!

**Comment by ptman** [comment]
so this is done and could be closed?
