### ISSUE TITLE
refresh token all works

### ISSUE THREAD

**Issue by fghjhuang** [go-oauth2/oauth2#77]
当用密码验证后返回refresh token1，然后用refresh token1去刷新；然后再用密码验证返回refresh token2，然后发现用refresh token1和refresh token2都可以进行刷新，是否应该生成refresh token2的时候要使refresh toekn1失效才合理？还是说我有什么地方配置错误？

**Comment by LyricTian** [comment]
对于你说的这种场景，目前的设计是不支持的。现在的设计每次通过密码模式生成令牌，之前的令牌是可用的，需要等到过期之后失效。你提的这个建议，后面我会尝试支持。谢谢！
