### ISSUE TITLE
Compile locally?

### ISSUE THREAD

**Issue by belvederechennai** [go-oauth2/oauth2#81]
How to compile locally so that the code can be customized?

go build ./...

oauth2/example/server/server.go:11:2: cannot find package "oauth2/errors" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/errors (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/errors (from $GOPATH)
oauth2/example/server/server.go:12:2: cannot find package "oauth2/manage" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/manage (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/manage (from $GOPATH)
oauth2/example/server/server.go:13:2: cannot find package "oauth2/models" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/models (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/models (from $GOPATH)
oauth2/example/server/server.go:14:2: cannot find package "oauth2/server" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/server (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/server (from $GOPATH)
oauth2/example/server/server.go:15:2: cannot find package "oauth2/store" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/store (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/store (from $GOPATH)
oauth2/generates/access.go:9:2: cannot find package "oauth2" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2 (from $GOROOT)
	/Users/z001dv3/go/src/oauth2 (from $GOPATH)
oauth2/generates/access.go:10:2: cannot find package "oauth2/utils/uuid" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/utils/uuid (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/utils/uuid (from $GOPATH)
oauth2/manage/manager.go:8:2: cannot find package "oauth2/generates" in any of:
	/usr/local/Cellar/go/1.10.1/libexec/src/oauth2/generates (from $GOROOT)
	/Users/z001dv3/go/src/oauth2/generates (from $GOPATH)

**Comment by LyricTian** [comment]
You can try this:

```
cd $GOPATH
mkdir -p gopkg.in/oauth2.v3
git clone https://github.com/go-oauth2/oauth2.git gopkg.in/oauth2.v3
cd  gopkg.in/oauth2.v3
go build ./...
```

**Comment by belvederechennai** [comment]
thanks, i had the packages define twice.
