### ISSUE TITLE
How do you think about function which offers id_token?

### ISSUE THREAD

**Issue by djKooks** [go-oauth2/oauth2#90]
Hello
How do you think about implementing function which offers id_token, in OpenID-connect specification(https://auth0.com/docs/tokens/id-token)?
I know this could not be fit to this project, because this is out of spec in OAuth2. But when I was implementing authentication server based on this module, I felt this could be useful.

Thanks.

**Comment by jakubknejzlik** [comment]
@djKooks I'm currently implementing ID token for this library using `ExtensionFieldsHandler`. Basically you check the scopes and generate the ID token in field:
```
srv.ExtensionFieldsHandler = func(ti oauth2.TokenInfo) (fieldsValue map[string]interface{}) {
        scope := ti.GetScope()
        if myContainsScopeCheck(scope, "openid") {
             fieldsValue = map[string]interface{}{}
	     fieldsValue["id_token"] = generateIDToken(ti.GetUserID(), scope)
	}
	return
}
```
Implementation is really straightforward, but it would be nice to have it in some sort of "plugin".

**Comment by jakubknejzlik** [comment]
Maybe this implementation details also help: https://github.com/graphql-services/oauth/commit/72f9aff1c2b82c485e1866c9afedecab69619b82

**Comment by djKooks** [comment]
@jakubknejzlik great! It seems simple enough~
Because there is no reaction...I'll close this one. But maybe someone get interested about this, you could suggest this to them.
