### ISSUE TITLE
Redis Storage

### ISSUE THREAD

**Issue by rps-repo** [go-oauth2/oauth2#97]
README.md says that the store can implement Redis.  Is this for both client and token storage?  Does the Redis package https://github.com/go-oauth2/redis do both?  If so how do you use it with clients?  The usage only shows an example for tokens.

**Comment by LyricTian** [comment]
The client is managed and distributed by the authorization service. Generally, the client can be managed independently according to its own usage mode, and some client authorization operations are performed. The token is requested by the client to the authorization service, and the token store can be fully hosted by the authorization service. So, with the client's use, you can implement the `ClientInfo` interface yourself.
